# Generated by Django 6.0.5 on 2026-06-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    # Below, note that Django inserts an id field for your tables, which is an auto increment number 
    # (first record gets the value 1, the second record 2 etc.), 
    # this is the default behavior of Django, you can override it by describing your own id field.
    operations = [
        migrations.CreateModel(
            name='Robotti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robotType', models.CharField(max_length=255)),
                ('robotModel', models.CharField(max_length=255)),
            ],
        ),
    ]

    # To see the SQL-statements that this migration will run, you can use the command:
    # python manage.py sqlmigrate robotit 0001