# Generated by Django 6.0.5 on 2026-06-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotti',
            name='added_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='robotti',
            name='robotIDnumber',
            field=models.IntegerField(null=True),
        ),
    ]
