# Generated by Django 6.1 on 2026-09-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotti',
            name='location_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='robotti',
            name='location_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
